# PickScore image-text preference reward.
reward:
  components:
    pickscore: 1.0
  kwargs:
    pickscore:
      processor_name: laion/CLIP-ViT-H-14-laion2B-s32B-b79K
      model_name: yuvalkirstain/PickScore_v1
      dtype: float32
