# Cosmos Predict2.5 2B PredictBase for DiffusionNFT RL.
model:
  family: cosmos-predict2.5
  path: nvidia/Cosmos-Predict2.5-2B
  revision: diffusers/base/post-trained
  skip_text_encoder: false

  use_lora: true
  lora:
    rank: 32
    alpha: 64
    path: ""
    target_modules:
      - to_k
      - to_out.0
      - to_q
      - to_v
      - ff.net.0.proj
      - ff.net.2

  torch_compile:
    enable: false
    mode: default
